
---

PlusPF:   "/mnt/san/microbio/database/kraken2/PlusPF20260226"
inspectPF: "/mnt/san/microbio/database/kraken2/PlusPF20260226/inspect.txt"
barlett:  "/mnt/san/microbio/database/gtdb/bartlett_index"
eupathdb: "/mnt/san/microbio/database/kraken2/eupathdb48_20230407"
inspect_eupathdb: "/mnt/san/microbio/database/kraken2/eupathdb48_20230407/inspect.txt"
threads:  15

lib3:
  polyt_literal: "TTTTTTTTT"
  polyt_kmer:    9
  polyt_hdist:   1
